import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.profitslab.io/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: "https://www.profitslab.io/products/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.profitslab.io/products/prompt-stack/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.profitslab.io/products/ai-sales-sequence-pack/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.profitslab.io/products/connector-wtf/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/sales-follow-up-email-sequence/",
      lastModified: new Date("2026-05-29"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-customer-service-prompts/",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/best-ai-tools-small-business/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://www.profitslab.io/guides/how-to-use-chatgpt-for-business/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://www.profitslab.io/guides/ai-prompts-for-sales/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-prompts-for-social-media/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/mcp-server-setup/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.profitslab.io/guides/ai-business-data-analysis/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/chatgpt-vs-jasper-small-business/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/write-sops-with-ai/",
      lastModified: new Date("2026-05-25"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/linkedin-outreach-templates-ai/",
      lastModified: new Date("2026-06-03"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/handling-sales-objections-ai/",
      lastModified: new Date("2026-06-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/cold-email-prompts/",
      lastModified: new Date("2026-06-05"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/repurpose-blog-post-into-content/",
      lastModified: new Date("2026-05-25"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-tools-vs-virtual-assistant/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/chatgpt-vs-claude-business/",
      lastModified: new Date("2026-05-24"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/meeting-notes-to-action-items/",
      lastModified: new Date("2026-06-12"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-contract-drafting/",
      lastModified: new Date("2026-06-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/onboarding-checklist-ai/",
      lastModified: new Date("2026-06-15"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/quarterly-planning-ai/",
      lastModified: new Date("2026-06-17"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/customer-response-templates/",
      lastModified: new Date("2026-06-26"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/competitor-analysis-chatgpt/",
      lastModified: new Date("2026-06-19"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/audit",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/audit/start",
      lastModified: new Date("2026-05-23"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.profitslab.io/guides/ai-product-descriptions/",
      lastModified: new Date("2026-06-29"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/train-chatgpt-brand-voice/",
      lastModified: new Date("2026-07-01"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-content-calendar/",
      lastModified: new Date("2026-07-01"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-tools-for-freelancers/",
      lastModified: new Date("2026-07-03"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-email-triage/",
      lastModified: new Date("2026-07-03"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-financial-forecasting/",
      lastModified: new Date("2026-07-06"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-market-research/",
      lastModified: new Date("2026-07-08"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/ai-prompts-for-marketing/",
      lastModified: new Date("2026-07-10"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/guides/claude-vs-gemini-business/",
      lastModified: new Date("2026-07-13"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.profitslab.io/privacy",
      lastModified: new Date("2026-01-01"),
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: "https://www.profitslab.io/terms",
      lastModified: new Date("2026-01-01"),
      changeFrequency: "yearly",
      priority: 0.2,
    },
  ];
}
